global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'attendance-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081'] # Assumes app runs on localhost:8081
